### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhengcaigou** [msartore/ATA-GUI#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - ATA Version
 - Adb Version

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3]
 - OS: [e.g. Android 11]

**Additional context**

**Comment by msartore** [comment]
Hi, can you fill the report so I can understand what bug you are encountering
