### ISSUE TITLE
[FEATURE] Edit build.prop on non-rooted devices

### ISSUE THREAD

**Issue by anlearntech** [msartore/ATA-GUI#27]
**Is your feature request related to a problem? Please describe.**
Is there any way ATA GUI can make a backup, edit, and push build.prop on Samsung device without root or TWRP?
I'm on Samsung S10+ (SM-G975N), and it's a disappointment that Samsung disabled multiple users. Editing build.prop seems like the way to go. However, it requires root or TWRP, and both method will surely trip Knox, and render Samsung Pay, as well as some other banking apps useless. As the phone is still functional with stock OS, I try to refrain from rooting or flash TWRP.

**Describe the solution you'd like**
According to this [article](https://www.xda-developers.com/add-multi-user-support-android/), I need to change 2 variables in the build.prop. I want to be able to get the build.prop file (to make a backup of it), change variable, and push it back, without tripping Knox.

**Describe alternatives you've considered**
Currently I get by with Insular + Secure Folder, so I get a total of 3 spaces at the same time (instead of the common 5 users' space limit). Switching is a bit of a hassle, too. I also look around and found that Samsung has activities ManagedProfile1-4, so either build.prop editing or other options that can create multiple work profiles can maybe work, too (currently Insular only allows for 1 space).

**Additional context**
I don't think this is relevant, but just for more info: I have another Xiaomi Mi CC 9 (A11), that used to have the multiple users features but disappear after unbricking. So I use App Manager (Fdroid) to access the Multiple Users settings at com.android.settings.Settings$UserSettingsActivity and create a user to reenable it. This however not worked on Samsung as that activity is show as disabled in AM, the closest I could find is Managed Profile when I have enabled Work Profile through Insular/Island/Shelter.

Thank you for the GUI. Intuitive and easy to use, even for noobs (like me). The functions on System tab alone are greatly helpful, right out of the box, without wiki or tutorial.
_P/S: please pardon my English, not mother-tongue, and the excessive information, as I'm no technologist._

**Comment by msartore** [comment]
Hi, I can implement a feature to edit the build.prop, but the requirement needed to make it works is to have access to the rooted debugging. If that option is not enabled, the device will refuse to let ATA-GUI pull and push from and to the system.

**Comment by anlearntech** [comment]
I see, so it has to have root permission nonetheless. Any root-related activity will most certainly trip the Knox fuse, so it isn't the path I'm willing to take right now.
Thank you for your time. Happy programming 😄

**Comment by anlearntech** [comment]
I see, so it has to have root permission nonetheless. Any root-related activity will most certainly trip the Knox fuse, so it isn't the path I'm willing to take right now.
Thank you for your time. Happy programming 😄
