### ISSUE TITLE
[BUG]hello

### ISSUE THREAD

**Issue by InternetRebelAKAQuachHungPhong** [msartore/ATA-GUI#29]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - ATA Version
 - Adb Version

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3]
 - OS: [e.g. Android 11]

**Additional context**

**Comment by msartore** [comment]
Request form not filled, closing issue. Please review it and re-open it when ready.
