### ISSUE TITLE
[RECURSO] Revoke granted permissions on APPS

### ISSUE THREAD

**Issue by marmmc** [msartore/ATA-GUI#8]
SOMETHING IMPORTANT
there is an option to grant permissions on APPS, but there is no option other than DUMP, and GRANT, to RETURN permissions...

in this case I GRANT all the APPS, and it doesn't open some apps anymore, I would have to have the REVOKE option for the APPS, ok...

**Comment by MassimilianoSartore** [comment]
New [pre-release version](https://github.com/MassimilianoSartore/ATA-GUI/releases/tag/v1.7.7_Pre-release) is available for testing

**Comment by marmmc** [comment]
tks
